### PR TITLE
align with indent guides

### PR DESCRIPTION
**Pull request by roshal**

### CODE REVIEW

**Comment by dima74** [comment]
Hi @roshal! Could you please add a bit context, why don't you like when rainbow is aligned with indent guides?

**Comment by roshal** [comment]
image

**Comment by roshal** [comment]
align

**Comment by roshal** [comment]
@dima74 to avoid a single pixel gap

**Comment by dima74** [comment]
> to avoid a single pixel gap

I think the plugin should automatically adjust the gap if indent guides are not shown. I implemented it in https://github.com/dima74/intellij-indent-rainbow/commit/d79d65dea3e303ef048941aeb6bf223587d8eb68, please update to latest version [2.1.0](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions/stable/260176) (available in 2022.3 IDE version)

**Pull request closed without merging**
