### PR TITLE
#46: Update platform to 2022.1.1

### PR DESCRIPTION
**Pull request by voom**

### CODE REVIEW

**Comment by voom** [comment]
@dima74 Could you please take a look at my PR? Thank you.

**Comment by dima74** [comment]
Hi @voom! Thanks for your PR
Plugin should be compatible with 2022.1 without any changes, at least I have no problems with installing and using `v2.0.2` in `2022.1`. Do you observe any problems with `2022.1`?

**Comment by dima74** [comment]
> 1.6-2020.1

It's too old version, could you please uninstall it, and install latest version 2.0.2?

**Comment by voom** [comment]
I've just upgraded to IJ IDEA 2022.1.2 and managed to install the plugin! 
These are the details:
IntelliJ IDEA 2022.1.2 (Ultimate Edition)
Build #IU-221.5787.30, built on May 31, 2022
Licensed to Vladislav Potapov
Subscription is active until December 6, 2022.
Runtime version: 11.0.15+10-b2043.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.6.0)
    com.jetbrains.edu (2022.5-2022.1-343)
    com.intellij.lang.puppet (221.5787.13)
    org.jetbrains.plugins.ruby (221.5787.20)
    org.jetbrains.kotlin (221-1.7.0-release-281-IJ5591.52)
    com.intellij.guice (221.5787.20)
    com.intellij.plugin.adernov.powershell (2.0.10)
    org.sonarlint.idea (6.7.0.45926)
    mobi.hsz.idea.gitignore (4.4.0)
    ClearCachePlugin (1.1)
    Osmorc (221.5787.20)
    MavenRunHelper (4.20.213.3714.1)
    izhangzhihao.rainbow.brackets (6.24)

Kotlin: 221-1.7.0-release-281-IJ5591.52

**Pull request closed without merging**
